# The URL the site will be built for
base_url = "https://www.example.com/"

title = "John Doe"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "solarized-light"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_rss = true

# Go through every link in all content and check if the links are valid. If a
# link is invalid (404, 500, etc), the build will error. Link checking can take
# a very long time if you have many links so this should only enabled once in a
# while to catch any dead links.
check_external_links = false

# Put all your custom variables here
[extra]
# The Title of the site
author = "John Doe"

# Links to include in the navigation bar
nav = [
  {name = "About", link = ""},
  {name = "CV", link = "cv.pdf"},
  {name = "Blog", link = "blog"},
]

# Your Google Analytics ID
analytics = ""

# See below
katex_enable = false

# See below
instantpage_enable = true

